# Generated by Django 4.1.2 on 2022-12-03 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_options'),
        ('menu', '0003_alter_fooditem_category'),
    ]

    operations = [
    ]
